ci: notarize: Add --subject to statement creation (#44)
* ci: notarize: Add --subject to statement creation

Related: #39

Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

* ci: notarize: on: pull request: Test against main PRs

Related: #39

Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

* Revert "ci: notarize: on: pull request: Test against main PRs"

Run actions/github-script@v6
Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
    at Function.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:585:23)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:522:71
    at new Promise (<anonymous>)
    at __webpack_modules__.8041.__awaiter (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:518:12)
    at Function.getIDToken (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:571:16)
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:421:46)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:133:71
    at new Promise (<anonymous>)
Error: Unhandled error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable

This reverts commit d4ea9eab83f35dddba73da73021137f73a9c8e5e.

---------

Signed-off-by: John Andersen <johnandersenpdx@gmail.com>